shared:
    environment:
        PYTHON_BOOTSTRAP_SKIP_PYPIRUN: 'True'
        PYTHON_BOOTSTRAP_SKIP_SCREWDRIVERCD: 'True'
    image: almalinux:8

jobs:
    publish_cmd:
        steps:
            - validate: |
                for cmd_filename in $(ls -1 sd-cmd/*.yaml)
                do
                    echo -n "${cmd_filename}: "
                    sd-cmd validate -f "${cmd_filename}"
                    echo
                done
            - publish: |
                tag="pre"
                if [ ! -z $SD_PULL_REQUEST ] ; then
                    tag="pr$SD_PULL_REQUEST"
                else
                    for cmd_filename in $(ls -1 sd-cmd/*.yaml)
                    do
                        echo -n "${cmd}: "
                        sd-cmd publish -f "${cmd_filename}" -t $tag
                        echo
                    done
                fi
        requires: [~pr, ~commit]

    promote_cmd:
        steps:
            - validate: |
                mkdir -p $SD_ARTIFACTS_DIR/logs/sd-cmd-validate
                for cmd in $(ls -1 sd-cmd/*.sh)
                do
                    echo "validate ${cmd}: "
                    sd-cmd exec python-2304/${cmd}@pre > $SD_ARTIFACTS_DIR/logs/sd-cmd-validate/${cmd}.log 2>&1
                    echo
                done
                sd-cmd exec python-2304/pypirun@pre serviceping serviceping --help
                sd-cmd exec python-2304/remoterun@pre https://edge.dist.yahoo.com:4443/artifactory/bootstrap/motd/motd-0.0.25508114
            - promote: |
                for cmd in $(ls -1 sd-cmd/*.sh)
                do
                    echo "promote ${cmd}: "
                    sd-cmd publish -f "sd-cmd/${cmd}.yaml" -t latest
                    sd-cmd publish -f "sd-cmd/${cmd}.yaml" -t stable
                    # sd-cmd promote python-2304/${cmd} pre latest
                    # sd-cmd promote python-2304/${cmd} pre stable
                  echo
                done
        requires: [publish_cmd]

    publish_base_template:
        image: almalinux:8
        environment:
            PYTHON_BOOTSTRAP_SKIP_PYPIRUN: True
            PYTHON_BOOTSTRAP_SKIP_SCREWDRIVERCD: False
            TEMPLATE_DIR: templates
            TEMPLATE_TAG: stable
            TEMPLATES_BASE: base.yaml
            TEMPLATES: base.yaml, packaging, utility, validation
        steps:
            - init_os: |
                sd-cmd python-2304/python_bootstrap@stable
                . $SD_ARTIFACTS_DIR/env/python_bootstrap.env
            - install_dependencies: $BASE_PYTHON -m screwdrivercd.installdeps
            - install: npm install screwdriver-template-main@1.7.0
            - set_base_templates: |
                ORIG_TEMPLATES="$TEMPLATES"
                TEMPLATES="$TEMPLATES_BASE"
            - validate_base: $BASE_PYTHON ci_scripts/process_templates.py validate
            - publish_base: $BASE_PYTHON ci_scripts/process_templates.py publish
            - set_templates: TEMPLATES="$ORIG_TEMPLATES"
            - validate: $BASE_PYTHON ci_scripts/process_templates.py validate
            - publish: $BASE_PYTHON ci_scripts/process_templates.py publish
        requires: [publish_cmd]
